### ISSUE TITLE
Design choices

### ISSUE THREAD

**Issue by frennkie** [arcbtc/lnbits#21]
I question the decision to use Python-Flask as (one of the) core backend components...

Any chance in switching this to Django? If so I would be happy to support..! :-D

**Comment by arcbtc** [comment]
Why do you think Django is a better choice?

**Comment by eillarra** [comment]
This started as a one file app in Flask, and it has evolved from there. I don't think Flask is going to be a limiting factor in this phase of the project, so I would not spend too much time on this.

If the project grows and we really see the need, we can consider other frameworks for v1.0. But then, even if I like Django and I use it every day, my vote would probably be for a lightweight API-first framework, with good async support: something like FastAPI, maybe.

I would love to have Django migrations instead of the hack we now have, or out of the box user accounts / login systems... but I think we can add solutions for these, without big efforts, to the current Flask application.

**Comment by frennkie** [comment]
So Django has better migrations, it includes an account system and an admin panel (both of which are on the `LNbits` roadmap, as far as I understand). It has an excellent API framework (with DRF) and there is some async support (although it's pretty fresh and not complete yet).

> LNbits was designed to be specifically lightweight, so to this end Flask is a good design choice

Well yes, but with the downside that more code must be written and maintained for `LNbits`.

But Flask is a good and lightweight framework and a lot is already implemented - so to avoid any further (religious) discussions I'll close the issue... :-D

**Comment by fiatjaf** [comment]
Flask is a thousand times better than Django!

Can we rewrite lnbits in Haskell? I think that would be nicer.

**Comment by sgeisler** [comment]
> Can we rewrite lnbits in Haskell?

Or Rust :P *duck and cover*

Joking aside, at some point having the core in a somewhat formally verifiable language might be interesting. The plugins could still run in their own python processes, shielded from the world, only allowed to communicate via specified APIs. But first there has to be enough traction and python seems ideal to onboard as many people as possible.
